import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import '@orderbook-visualizer/ui/globals.css';

import LayoutRoot from '@/components/layout/Root';
import Providers from '@/providers';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Simple Next.js with ShadCN UI Starter',
  description: 'Generated by @fapiper',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Providers>
          <LayoutRoot>{children} </LayoutRoot>
        </Providers>
      </body>
    </html>
  );
}
